server:
  port: 20001
spring:
  jpa:
    hibernate:
      ddlAuto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/async?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    initialization-mode: always
  profiles:
    active: stream-rabbitmq