server:
  port: 20001
spring:
  jpa:
    hibernate:
      ddlAuto: create
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:21746/async?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  sql:
    init:
      mode: always
  profiles:
    active: stream-rabbitmq