spring:
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: 1234
    virtual-host: test-virtual-host
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        subscribeChannel:
          binder: rabbit
          destination: payrequest
          group: pay
          queueNameGroupOnly: true
          producer:
            required-groups: pay
        resultCheannel:
          binder: rabbit
          destination: resultChannel
          group: result
          queueNameGroupOnly: true
        deadLetterChannel:
          binder: rabbit
          destination: dead-letter-queue
          queueNameGroupOnly: true
          group: dlq
          producer:
            required-groups: dlq