spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        subscribeChannel:
          binder: kafka
          destination: payrequest
          producer:
            required-groups: test-queue
          group: result
        resultCheannel:
          binder: kafka
          destination: resultChannel
          producer:
            required-groups: test-queue
          group: result
        deadLetterChannel:
          binder: kafka
          destination: dead-letter-queue
          producer:
            required-groups: test-queue
          group: result